### ISSUE TITLE
Er ontbreken gegevens in een Node

### ISSUE THREAD

**Issue by DaniKemper** [sfkelder/Model_Way2gO#1]
Om de juiste informatie te laten zien in bij de tussenstations, mis ik wat gegevens die ik graag in de Node erbij wil hebben. Ik mis namelijk de informatie op welk **perron** de trein aankomt/ vertrekt op een Node. Ook mis ik de **vertrektijd** van de trein op een Node. Graag zie ik dit aangepast worden.

**Comment by wettacked** [comment]
toegevoegd
