### ISSUE TITLE
Ontbreken gegevens in de Route Class

### ISSUE THREAD

**Issue by DaniKemper** [sfkelder/Model_Way2gO#2]
Om de juiste informatie te laten zien, zoals wij in ons prototype hebben mis ik wat gegevens in de Route Class. Zo mis ik wat de **naam** van de **vervoerder** is, bijvoorbeeld "**NS**" en mis ik informatie over de **naam** van de **soort** **trein** of het een "**intercity**" is of "**sprinter**" ect. Graag zou ik dit erbij willen als dit mogelijk is.

**Comment by wettacked** [comment]
toegevoegd
